-   id: pretty-toml-sort
    name: pretty-toml-sort
    entry: pretty-toml-sort
    args: [--check]
    language: python
    types: [toml]
-   id: pretty-toml-sort-fix
    name: pretty-toml-sort-fix
    entry: pretty-toml-sort
    args: [--in-place]
    language: python
    types: [toml]
